# Kanagawa theme for btop

# Main background, empty for terminal default
theme[main_bg]="#1F1F28"

# Main text color
theme[main_fg]="#DCD7BA"

# Title color for boxes
theme[title]="#DCD7BA"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#957FB8"

# Background color of selected item in processes box
theme[selected_bg]="#2A2A37"

# Foreground color of selected item in processes box
theme[selected_fg]="#DCD7BA"

# Color of inactive/disabled text
theme[inactive_fg]="#54546D"

# Color of text appearing on top of graphs
theme[graph_text]="#C8C093"

# Background color of the percentage meters
theme[meter_bg]="#363646"

# Misc colors for processes box including mini cpu graphs
theme[proc_misc]="#7E9CD8"

# Cpu box outline color
theme[cpu_box]="#957FB8"

# Memory/disks box outline color
theme[mem_box]="#7E9CD8"

# Net up/down box outline color
theme[net_box]="#98BB6C"

# Processes box outline color
theme[proc_box]="#C0A36E"

# Box divider line and small boxes line color
theme[div_line]="#363646"

# Temperature graph colors
theme[temp_start]="#98BB6C"
theme[temp_mid]="#E6C384"
theme[temp_end]="#C34043"

# CPU graph colors
theme[cpu_start]="#957FB8"
theme[cpu_mid]="#7E9CD8"
theme[cpu_end]="#98BB6C"

# Mem/Disk free meter
theme[free_start]="#76946A"
theme[free_mid]="#98BB6C"
theme[free_end]="#98BB6C"

# Mem/Disk cached meter
theme[cached_start]="#957FB8"
theme[cached_mid]="#7E9CD8"
theme[cached_end]="#7FB4CA"

# Mem/Disk available meter
theme[available_start]="#C0A36E"
theme[available_mid]="#E6C384"
theme[available_end]="#FFA066"

# Mem/Disk used meter
theme[used_start]="#E46876"
theme[used_mid]="#C34043"
theme[used_end]="#C34043"

# Download graph colors
theme[download_start]="#957FB8"
theme[download_mid]="#7E9CD8"
theme[download_end]="#7FB4CA"

# Upload graph colors
theme[upload_start]="#76946A"
theme[upload_mid]="#98BB6C"
theme[upload_end]="#98BB6C"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#957FB8"
theme[process_mid]="#7E9CD8"
theme[process_end]="#54546D"
